/// Device Model class
class DeviceModel {

  /// Constructor to create a DeviceModel instance
  DeviceModel({
    required this.firebaseToken,
    required this.device,
    required this.so,
    required this.model,
    required this.id,
  });

  /// Factory method to create a DeviceModel instance from a json
  factory DeviceModel.fromJson(Map<String, dynamic> json) {
    return DeviceModel(
      firebaseToken: json['firebaseToken'] != null ? json['firebaseToken'].toString() : '',
      device: json['device'] != null ? json['device'].toString() : '',
      so: json['so'] != null ? json['so'].toString() : '',
      model: json['model'] != null ? json['model'].toString() : '',
      id: json['_id'] != null ? json['_id'].toString() : '',
    );
  }

  /// [firebaseToken] is the token generated by Firebase Messaging
  String firebaseToken;

  /// [device] is the device brand
  String device;

  /// [so] is the device operating system
  String so;

  /// [model] is the device model
  String model;

  /// [_id] is the device id
  String id;
}
